name: OTEL Action Test

on:
  push:
  pull_request:

jobs:
  trace-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GO
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"

      - name: Install tracegen
        run: go install github.com/open-telemetry/opentelemetry-collector-contrib/tracegen@latest

      - name: Run tracegen
        run: tracegen -duration 5s -otlp-http -otlp-endpoint ${secrets.ENDPOINT}
