name: OTEL Action Test

on:
  push:
  pull_request:

jobs:
  job1:
    name: Random Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Do some random work
        run: sleep $[$RANDOM % 10].$[$RANDOM % 10]s

  job2:
    name: Random Job 2
    runs-on: ubuntu-latest
    steps:
      - name: Do some random work
        run: sleep $[$RANDOM % 10].$[$RANDOM % 10]s

  test-action:
    name: Test OTEL action
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4

      - name: Run otel-action
        uses: inception-health/otel-export-trace-action@latest
        with:
          otlpEndpoint: ${{ secrets.ENDPOINT }}
          otlpHeaders: ${{ secrets.HEADERS }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
